### ISSUE TITLE
INITIAL_ADMIN_EMAIL with upper case character results in Invalid email or password

### ISSUE THREAD

**Issue by JMDirksen** [NginxProxyManager/nginx-proxy-manager#4665]
**Checklist**
- Have you pulled and found the error with `jc21/nginx-proxy-manager:latest` docker image?
  - Yes
- Are you sure you're not using someone else's docker image?
  - Yes
- Have you searched for similar issues (both open and closed)?
  - Yes

**Describe the bug**
When using the **INITIAL_ADMIN_EMAIL** environment variable with an email address with upper case characters you are not allowed to login (_Invalid email or password_) because it expects to find the email address with only lower case characters in the database.

**Nginx Proxy Manager Version**
v2.12.6

**To Reproduce**
1. Set environment variable INITIAL_ADMIN_EMAIL with an upper case character
```
      INITIAL_ADMIN_EMAIL: Admin@example.com
      INITIAL_ADMIN_PASSWORD: changeme
```
2. `docker compose up`
Shows: `Creating a new user: Admin@example.com with password: changeme`
3. Try to login with either admin@example.com or Admin@example.com
Result: _Invalid email or password_

**Expected behavior**
Since the rest of the application does a toLowerCase() before changing the email in the database the initial setup.js should also do a toLowerCase() on the environment variable

I've created a PR #4664 but it didn't build.

**Comment by robinmalik** [comment]
Hitting this too. Thanks for figuring out the root cause.

**Comment by JeftaDirksen** [comment]
You're welcome, it got fixed in the update that was released today v2.13.0 #4825

**Comment by GlobularCluster12** [comment]
i got the issue still and i'm not too sure how to fix it :/ its confusing and i dont know how to go about this

**Comment by GlobularCluster12** [comment]
https://www.reddit.com/r/nginxproxymanager/comments/1pei5sv/admin_account_problems_with_password_on_new/

this is also how i went about fixing it
