### ISSUE TITLE
Cannot specify ciphers?

### ISSUE THREAD

**Issue by sbazzell** [NginxProxyManager/nginx-proxy-manager#564]
Whenever I try to specify ciphers the way I would normally do using nginx vanilla, the proxy host goes to offline status.

So does

> ssl_ciphers 'insert cipher list here';

and

> ssl_prefer_server_ciphers on;

not work?

**Comment by dash74** [comment]
It looks like the only was too edit the ciphers would be to edit /etc/nginx/conf.d/include/ssl-ciphers.conf inside the docker container. You can do this by running docker exec -it "docker-name" bash. After editing the file you type exit. You'll have to commit the changes to a new file by running sudo docker commit [CONTAINER_ID] [new_image_name].

**Comment by Mattie112** [comment]
Yes I also want to change the ciphers. Any chance we can have this also exported in a volume just like the (optional) config files.

**Comment by Mattie112** [comment]
I did find a solution / workaround.

Simply create your own cipher file (outside of the container), for example generate it here https://ssl-config.mozilla.org/ but only use the protocols/ciphers part.

Now simply mount this file into the container
`/etc/nginx/conf.d/include/ssl-ciphers.conf:/mnt/user/appdata/NginxProxyManager/myown-custom-ssl-ciphers.conf`

And now you have your own ciphers. Downside is that this no longer benefits from updates from the NPM itself. So you might want to check https://github.com/jc21/nginx-proxy-manager/blob/master/docker/rootfs/etc/nginx/conf.d/include/ssl-ciphers.conf from time to time to check your file is up to date.

**Comment by Mattie112** [comment]
![image](https://user-images.githubusercontent.com/662896/161726289-880b8bd5-7985-4866-ad65-8da1e8481ace.png)

You should be able to just type it in :)

**Comment by Kopernikus1979** [comment]
> ![image](https://user-images.githubusercontent.com/662896/161726289-880b8bd5-7985-4866-ad65-8da1e8481ace.png)
> 
> You should be able to just type it in :)

Hi,

Tried it, but I get this error in my docker log:

![Schermafbeelding 2022-04-05 153922](https://user-images.githubusercontent.com/53930186/161767121-7febcca0-7e75-4df4-9c23-e673aab6f034.jpg)

If I go to /etc/nginx/conf.d/include/ssl-ciphers.conf I see it's my new modded file, however settings are not loaded when doing cryptcheck.fr for my domain

**Comment by Mattie112** [comment]
Can you run `docker inspect NginxProxyManager`

And check the following part:
```
        "HostConfig": {
            "Binds": [
                "/mnt/user/appdata/NginxProxyManager/matthijs-custom-ssl-ciphers.conf:/etc/nginx/conf.d/include/ssl-ciphers.conf:rw",
                "/mnt/user/appdata/NginxProxyManager:/config:rw"
            ],
```

You can see how I have it and that does work. Does it look different for you?

**Comment by Kopernikus1979** [comment]
Yes looks the same except for the /config who is data and the docker image
It seems I'm using Nginx-Proxy-Manager-Official docker and you are using NginxProxyManager

**Comment by Kopernikus1979** [comment]
Just found something strange seems in the lastest version of NPM the ciphers are already compliant with the latest mozilla recommends, however when doing a check it still uses old ciphers, can you do a cryptcheck to see your result?

**Comment by Mattie112** [comment]
Ah yeah might be fair to say I use this repo:

https://github.com/Mattie112/docker-nginx-proxy-manager (and that is a fork of https://github.com/jlesage/docker-nginx-proxy-manager)

I think it uses / used to use this project but yeah that was a while ago..... So it could be that here the paths are changed, sorry can't keep track on what repo I use exactly :p

Anyway, my file:

```
ssl_session_timeout 5m;
ssl_session_cache shared:SSL:50m;

# intermediate configuration. tweak to your needs.
    # intermediate configuration
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384;
    ssl_prefer_server_ciphers off;

```

I always use https://www.ssllabs.com/ssltest/ for checking (A+ for me) but here is the output from your site:

![image](https://user-images.githubusercontent.com/662896/161817981-3552ea58-345a-49e5-9d63-5ae30113b505.png)

**Comment by Kopernikus1979** [comment]
@Mattie112 

Hi,

I found the problem.
See my bug report:

https://github.com/NginxProxyManager/nginx-proxy-manager/issues/1982

So until this is fixed in the jc21 version I would use your fork or the jlesage version since I also need ports 80/443 exposed inside the container, however I saw your version is outdated, would you be able to update it to the lastest version?

Thx

**Comment by Mattie112** [comment]
Yeah I'm doing that manually from time to time XD Have to look into github pipelines (or whatever it is called) at some point.

I just pushed `mattie112/docker-nginx-proxy-manager:latest` (and `:master` and `:v1.26.0`) to be up-to-date with jlesage again :)

(And the reason I made my own fork because I kinda liked the all-in-one solution but I needed 80/443 so yeah I just choose this solution).

**Comment by Xyz00777** [comment]
this is as far as i know still not working :(
when does these can be fixed?

**Comment by Sokratis1904** [comment]
The problem also exists with the latest version of NPM.
